name: update-ddbb

on:
  schedule:
    - cron: '0 0/6 * * *' #Execute every 6 hours
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:

      - name: Access the repo
        uses: actions/checkout@v3

      - name: Configure Python
        uses: actions/setup-python@v3 
        with:
          python-version: '3.11.1'

      - name: Install necessary libraries
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Execute Python Script
        env:
          URI: ${{ secrets.URI }}
        run: python etl_process.py
